source 'https://rubygems.org'

gem 'rails', '4.2.4'

gem 'rails-api'

gem 'pg'

gem 'active_model_serializers', '0.8.3'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'jbuilder', '~> 2.0'


group :test do
  gem 'coveralls', require: false
  gem 'database_cleaner'
end

group :development, :test do
  gem "pry-rails"
  gem 'rspec-rails'
  gem 'capybara'
  gem 'launchy'
  gem 'factory_girl'
  gem 'valid_attribute'
  gem 'shoulda-matchers', require: false
end

gem 'rails_12factor', group: :production
