source 'https://rubygems.org'

gem 'rails', '4.2.4'

gem 'rails-api'

gem 'pg'

gem 'active_model_serializers', '0.8.3'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'jbuilder', '~> 2.0'


group :test do
  gem 'shoulda-matchers', require: false
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.0.0'
end

gem 'rails_12factor', group: :production
